### PR TITLE
Fixed many traits bugs

### LINKED ISSUE #577: Trait method aliases broken
Hi,
consider this example: https://3v4l.org/a2hQf

Two observations from that:

1) Aliased trait method fetched on another trait should have the aliased name, not the original name.
2) Class that uses a trait with an aliased method should also know the aliased method.

Unfortunately, BetterReflection breaks both of those assumptions. Here's a reproducing example: https://gist.github.com/ondrejmirtes/a8481b8e03880aebd4e0bae5c6d87e86

### PR DESCRIPTION
**Pull request by kukulich**
Fixes #577

### CODE REVIEW

File: src/Reflection/ReflectionClass.php [hunk 1]
```diff
@@ -236,7 +244,10 @@ public function getExtensionName() : ?string
      */
     private function getAllMethods() : array
     {
-        return array_merge(
+        $traitAliases     = $this->getTraitAliases();
+        $traitPrecedences = $this->getTraitPrecedences();
+
+        return array_filter(array_merge(
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php:250]: would put the `array_filter()` only around the logic that fetches methods from traits

File: src/Reflection/ReflectionClass.php [hunk 2]
```diff
@@ -251,19 +262,54 @@ function (ClassMethod $methodNode) : ReflectionMethod {
...
-                            $trait,
-                            $this
-                        );
-                    }, $trait->getMethods());
+                function (ReflectionClass $trait) use ($traitAliases, $traitPrecedences) : array {
+                    return array_merge(
+                        [],
+                        ...array_filter(
+                            array_map(
+                                function (ReflectionMethod $method) use ($traitAliases, $traitPrecedences) : ?array {
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php:270]: this logic now contains looping and more complex checks: we need it to be split out into a `private` method

File: src/Reflection/ReflectionClass.php [hunk 3]
```diff
@@ -251,19 +262,54 @@ function (ClassMethod $methodNode) : ReflectionMethod {
...
+                                    $methodAst = $method->getAst();
+                                    assert($methodAst instanceof ClassMethod);
+
+                                    $aliases = [];
+                                    foreach ($traitAliases as $aliasMethodName => $traitAliasDefinition) {
+                                        if (sprintf('%s::%s', $method->getDeclaringClass()->getName(), $method->getName()) !== $traitAliasDefinition) {
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php:276]: the `%s::%s` approach for lookups seems very fragile: I see that it is pre-existing, but indeed unfortunate storage mechanism.

I would stash this out into a `private function methodHash(ReflectionClass $declaringClass, ReflectionMethod $method)` or such

File: src/Reflection/ReflectionClass.php [hunk 4]
```diff
@@ -984,12 +1015,60 @@ static function (ReflectionClass $trait) : string {
...
+     * class Foo
+     * {
+     *     use MyTrait, MyTrait2 {
+     *         MyTrait2::foo insteadof MyTrait1;
+     *     }
+     * }
+     * // This method would return
+     * //   ['MyTrait1::foo' => 'MyTrait2::foo']
+     */
+    public function getTraitPrecedences() : array
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php:1043]: we should probably **not** expose this API. It is complex enough to require complex examples, and I can't see a use-case for it where downstream would care about trait precedence?

File: src/Reflection/ReflectionClass.php (hunk 3 above)
Comment (Ocramius) [reply src/Reflection/ReflectionClass.php:276]: Seems to be done in a closure below, called `$formatMethodName`: we could use the same in `private` API

File: src/Reflection/ReflectionClass.php [hunk 5]
```diff
@@ -1001,23 +1080,15 @@ public function getTraitAliases() : array
...
 
-                if (! ($adaptation instanceof Node\Stmt\TraitUseAdaptation\Alias)) {
-                    continue;
-                }
-
-                if (! $adaptation->newName) {
-                    continue;
+                if ($adaptation instanceof Node\Stmt\TraitUseAdaptation\Alias && $adaptation->newName) {
+                    $this->cachedTraitAliases[$adaptation->newName->name] = $formatMethodName($usedTrait, $adaptation->method);
+                } elseif ($adaptation instanceof Node\Stmt\TraitUseAdaptation\Precedence && $adaptation->insteadof) {
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php:1085]: let's use a `continue` rather than an `elseif`

File: src/Reflection/ReflectionClass.php [hunk 6]
```diff
@@ -984,12 +1015,60 @@ static function (ReflectionClass $trait) : string {
...
+        return $this->cachedTraitPrecedences;
+    }
+
+    private function parseTraitUsages() : void
+    {
+        if ($this->cachedTraitAliases !== null && $this->cachedTraitPrecedences !== null) {
+            return;
+        }
+
+        $formatMethodName = static function (Node\Name $className, Identifier $methodName) : string {
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php:1057]: suggested above: let's move this to `private static` API.

necessary to mark it with `@psalm-pure`.

File: test/unit/Reflection/ReflectionClassTest.php [hunk 7]
```diff
@@ -941,26 +954,18 @@ public function testMethodsFromTraits() : void
 
         $classInfo = $reflector->reflect('TraitFixtureC');
 
-        self::assertTrue($classInfo->hasMethod('a'));
+        self::assertFalse($classInfo->hasMethod('a'));
```
Comment (Ocramius) [inline test/unit/Reflection/ReflectionClassTest.php:957]: was this an actual bug? very difficult to see it, given the change in the fixtures: maybe split them instead, so that old tests aren't affected?

Comment (Ocramius) [reply test/unit/Reflection/ReflectionClassTest.php:957]: never mind: original test was indeed wrong here!

**Comment by Ocramius** [comment]
Note: review is mostly around implementation details. Implementation is working, although the trait logic makes it very confusing.

hoping that stashing more details in separate `private` API could make it more clear

**Comment by kukulich** [comment]
@Ocramius Everything resolved (I hope). I will squash everything to one commit after second round of your review.

File: src/Reflection/ReflectionClass.php [hunk 8]
```diff
@@ -279,6 +285,55 @@ static function (ReflectionClass $ancestor) : array {
...
+                $aliasMethodName
+            );
+        }
+
+        if ($aliases !== []) {
+            return $aliases;
+        }
+
+        if (array_key_exists($methodHash, $traitPrecedences)) {
+            return null;
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php:322]: Would it make sense to return `[]` here too? Or is there a specific rationale for returning `null|[]`?

Comment (kukulich) [reply src/Reflection/ReflectionClass.php]: There were approximately 50 versions of the code before I sent the PR - I've almost killed @ondrejmirtes for finding more and more strange bugs :)

So it was just a residue.

Removed and squashed.

Comment (ondrejmirtes) [reply src/Reflection/ReflectionClass.php]: Don't blame me, blame PHP :)

Comment (Ocramius) [reply src/Reflection/ReflectionClass.php]: Blame decades of development in a dynlang :P

Comment (kukulich) [reply src/Reflection/ReflectionClass.php]: We also reported one PHP bug https://bugs.php.net/bug.php?id=79605 (already fixed in PHP 8)

**Comment by Ocramius** [comment]
Static analysis passed: not waiting for the rest :D

**Comment by Ocramius** [comment]
Thanks @kukulich!
