### PR TITLE
Fix exception being thrown in AutoloadSourceLocator

### LINKED ISSUE #234: AutoloadSourceLocator#locateFunctionByName should return `null`
```php
private function locateFunctionByName($functionName)
{
    if (!function_exists($functionName)) {
        throw new FunctionUndefined('Function ' . $functionName . ' was not already defined');
    }

    $reflection = new \ReflectionFunction($functionName);
    return $reflection->getFileName();
}
```

This should not throw an exception, it should `return null;` instead. A source locator should not throw an exception unless something is drastically wrong (e.g. misconfiguration of it); a SL should either return the located item, or return `null` (success or fail, not error state).

It's important because the `AutoloadSourceLocator` can't autoload a function unless it's already in memory, but if you have a later source locator that *could* find that same identifier (in an aggregate), then you're breaking the chain.

### PR DESCRIPTION
**Pull request by asgrim**
The handling in FunctionReflector was actually wrong - it was returning `null` when it should be throwing an `IdentifierNotFound` exception. In the case of using AutoloadSourceLocator when reflecting on a function, an exception `FunctionUndefined` was being thrown. This has been removed (therefore this is sadly a minor BC break) and we handle this correctly.

Fixes #234

### CODE REVIEW

File: src/SourceLocator/Exception/FunctionUndefined.php [hunk 1]
```diff
@@ -1,7 +0,0 @@
-<?php
-
-namespace Roave\BetterReflection\SourceLocator\Exception;
-
-class FunctionUndefined extends \RuntimeException
```
Comment (Ocramius) [inline src/SourceLocator/Exception/FunctionUndefined.php]: Deprecate, don't drop

**Comment by asgrim** [comment]
@Ocramius fixed; ready to review whenever build decides to complete :)

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 2]
```diff
@@ -95,13 +94,12 @@ class_exists($className);
...
      * @param string $functionName
-     * @return string
-     * @throws FunctionUndefined
+     * @return string|null
      */
     private function locateFunctionByName($functionName)
     {
         if (!function_exists($functionName)) {
-            throw new FunctionUndefined('Function ' . $functionName . ' was not already defined');
+            return null;
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php]: Also after this block: https://3v4l.org/vJkTR

```php
(new ReflectionFunction('preg_match'))->getFileName()
```

This produces `false`, not `null`. Can you factor it in?

Comment (asgrim) [inline src/SourceLocator/Type/AutoloadSourceLocator.php]: @Ocramius this isn't relevant yet, and also won't work (we can't yet reflect internal functions - see #38) so it doesn't affect us yet, and is also irrelevant for this PR

Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php]: Moved to https://github.com/Roave/BetterReflection/issues/237

**Comment by Ocramius** [comment]
👍
