### PR TITLE
`AutoloadSourceLocator` should support `phar://` paths as well as `file://`

### LINKED ISSUE #574: AutoloadSourceLocator::locateClassByName - does not work with files loaded from PHAR
You can imagine how long it took me to figure this out :)

Steps to reproduce:

1) Have an autoloader that contains paths to a PHAR, so they start with `phar://`.
2) Use AutoloadSourceLocator with the magic stream wrappers thing.
3) When locating a class, it's possible that `include` is triggered and that `include` is actually executed because it's handled by a `phar` wrapper, not `file` wrapper.
4) It'll probably end up in some fatal error because we're in a special "not actually loading files" mode, the autoloading cannot be triggered recursively again.

So for example:

* BR is asked for reflection of class `A`.
* BR tries to find its parent `B` that's inside a PHAR.
* `include phar://B.php` is actually executed.
* The class `B` extends class `C` also from inside the PHAR.
* Fatal error - class `C` not found although under normal circumstances, it'd be loaded because the autoloader knows about it.

I'm also gonna try to reproduce it although it might require to commit some small PHAR file to `tests`.

Verified proof of concept fix: https://github.com/ondrejmirtes/BetterReflection/commit/e909d2a273e23c96847cbeeb2c1da8846d71a946

### PR DESCRIPTION
**Pull request by kukulich**
Fixes #574
Fixes #576 

Credit to @ondrejmirtes :)

### CODE REVIEW

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 1]
```diff
@@ -183,14 +183,16 @@ private function locateClassByName(string $className) : ?string
             stream_wrapper_register($protocol, self::class);
         }
 
-        class_exists($className);
+        try {
+            class_exists($className);
+        } finally {
```
Comment (ondrejmirtes) [inline src/SourceLocator/Type/AutoloadSourceLocator.php:188]: This is needed when the autoloader throws an exception which would ideally have also a test case.

Also, I later found out that autoloaders that use a `require` instead of `include` are problematic and still end in fatal error. It helped:

1) to use `restore_error_handler()` instead of `set_error_handler($previousErrorHandler)` although I'm not sure why.
2) instead of `return true` in the error handler I'm throwing and catching an exception immediately: https://github.com/phpstan/phpstan-src/commit/83bbc8122a7286b86f01288fa85957f34378814c#diff-b84fb81e70db3cdb6b4495c80b475a44 Another advantage of the exception is that only the first of the registered autoloaders is hit and not all of them. The `require` still throws a warning on older PHP versions but it's fixed in 7.4.2 (https://3v4l.org/CkDDJ). I didn't find a better solution.

Comment (ondrejmirtes) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:188]: (This is what happens with the current code and unsuccessful require: https://3v4l.org/Nt7Ya)

Comment (asgrim) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:188]: > use `restore_error_handler()` instead of `set_error_handler($previousErrorHandler)`

Yeah that seems a bit of an oversight, looks like a reasonable fix

> instead of `return true` in the error handler I'm throwing and catching an exception immediately

wow :vomiting_face: but still, it's all a big smashing hack, so understandable. Let's go with the throwing exception mechanism to solve those edge cases :+1:

Comment (kukulich) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:198]: > use restore_error_handler() instead of set_error_handler($previousErrorHandler)

We cannot use `restore_error_handler()` because of `AutoloadSourceLocator::url_stat()`

> instead of return true in the error handler I'm throwing and catching an exception immediately

@ondrejmirtes See "WIP" commit please. Tests are failing. Did I missed something?

**Comment by kukulich** [comment]
This PR contains also #602 because we need to fix unrelated hidden bugs to have green build here.

I think this PR can be merged so we don't have hidden bugs again. `AutoloadSourceLocator` can be improved in another PR to fix #573.

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 1 above)
Comment (kukulich) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:187]: `restore_error_handler()` added. See comment below.

File: src/Reflection/ReflectionClass.php [hunk 2]
```diff
@@ -1472,7 +1473,7 @@ public function removeMethod(string $methodName) : bool
     public function addMethod(string $methodName) : void
     {
         $this->node->stmts[] = new ClassMethod($methodName);
-        unset($this->cachedMethods);
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php:1475]: Oh wow, this was ugly, and most likely unintended!

File: src/Reflection/StringCast/ReflectionClassConstantStringCast.php [hunk 3]
```diff
@@ -18,14 +17,13 @@ final class ReflectionClassConstantStringCast
...
         $value = $constantReflection->getValue();
-        assert($value === null || is_scalar($value));
 
         return sprintf(
             "Constant [ %s %s %s ] { %s }\n",
             self::visibilityToString($constantReflection),
             gettype($value),
             $constantReflection->getName(),
-            (string) $value
+            is_array($value) ? 'Array' : (string) $value
```
Comment (Ocramius) [inline src/Reflection/StringCast/ReflectionClassConstantStringCast.php:26]: This is un-tested: we should verify that:

```

class A {
    const B = ['C'];
}

var_dump((new ReflectionClassConstant(A::class, 'B'))->__toString());
```

Produces

```
string(38) "Constant [ public array B ] { Array }
"
```

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 4]
```diff
@@ -163,18 +174,34 @@ private function locateClassByName(string $className) : ?string
...
-        set_error_handler($previousErrorHandler);
+
+        $this->setErrorHandler();
+
+        foreach ($this->streamWrapperProtocols as $protocol) {
+            stream_wrapper_unregister($protocol);
+            stream_wrapper_register($protocol, self::class);
+        }
+
+        try {
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php:185]: We should verify this `try-finally` by adding a throwing autoloader to the stack.

The test would be something like:

```php
$toBeThrown = new SpecificExceptionType();

spl_autoload_register(static function () use ($toBeThrown) {
    throw $toBeThrown;
});

try {
    // ... try to locate symbol
    self::fail('No exception was thrown');
} catch (SpecificExceptionType $caught) {
    self::assertSame($toBeThrown, $caught);
}

// verify error handler and stream wrapper here
```

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 5]
```diff
@@ -163,18 +174,34 @@ private function locateClassByName(string $className) : ?string
...
-        $previousErrorHandler      = set_error_handler(static function (int $errno, string $errstr) : bool {
-            return true;
-        });
-        stream_wrapper_unregister('file');
-        stream_wrapper_register('file', self::class);
-        class_exists($className);
-        stream_wrapper_restore('file');
-        set_error_handler($previousErrorHandler);
+
+        $this->setErrorHandler();
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php:178]: The internal function is `set_error_handler()`, but what we do on our end is silencing the error handler.

We should therefore call this `->silenceErrors()` or such

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php [hunk 6]
```diff
@@ -302,4 +308,77 @@ public function autoload(string $className) : bool
...
+        try {
+            (new AutoloadSourceLocator($this->astLocator))
+                ->locateIdentifier(
+                    $this->getMockReflector(),
+                    new Identifier('Whatever', new IdentifierType(IdentifierType::IDENTIFIER_CLASS))
+                );
+
+            self::fail();
+        } finally {
+            spl_autoload_unregister($brokenAutoloader);
```
Comment (Ocramius) [inline test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php:381]: We need to verify that the previous stream wrapper and error handler are restored at this point

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 4 above)
Comment (Ocramius) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:185]: Errata: test already in place, just needs a couple assertions more :+1:

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php [hunk 7]
```diff
@@ -302,4 +308,77 @@ public function autoload(string $className) : bool
 
         return true;
     }
+
+    /**
+     * @runInSeparateProcess
+     */
+    public function testPharWorks() : void
```
Comment (Ocramius) [inline test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php:315]: `testWillLocateSourcesInPharPath`

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php [hunk 8]
```diff
@@ -302,4 +308,77 @@ public function autoload(string $className) : bool
...
+        });
+
+        $a = new AutoloadableClassInPhar();
+        $this->assertInstanceOf(AutoloadableClassInPhar::class, $a);
+    }
+
+    /**
+     * @runInSeparateProcess
+     */
+    public function testPharDoesNotWork() : void
```
Comment (Ocramius) [inline test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php:333]: Wording here needs adjustment - is it verifying that the source is not inside the phar?

File: test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php [hunk 9]
```diff
@@ -162,7 +163,7 @@ public function testCanFetchInternalLocatedSourceForConstants(string $constantNa
             $this->getMockReflector(),
             new Identifier($constantName, new IdentifierType(IdentifierType::IDENTIFIER_CONSTANT))
         );
-        assert($reflection instanceof ReflectionFunction);
+        assert($reflection instanceof ReflectionConstant);
```
Comment (Ocramius) [inline test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php:166]: Good catch!

**Comment by Ocramius** [comment]
Note: I think most of the new comments are to be handled in #602 rather than here, and instead we just rebase them out.

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 4 above)
Comment (kukulich) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:185]: I don't know how to test "verify error handler and stream wrapper here"

Both don't have "get" function.

For error handler I can do something like this:

```
        $previousErrorHandler = set_error_handler(function () {
            return true;
        });
        restore_error_handler();
```

However it's very ugly.

Comment (Ocramius) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:185]: The code for the "previous error handler" is exactly like that.

For the stream wrappers, maybe `stream_get_wrappers()`?

Comment (kukulich) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:185]: It only returns the list of registered wrappers.

Comment (Ocramius) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:185]: Guess we can't test that detail then :shrug:

Comment (Ocramius) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:185]: Actually: we can! `file_get_contents(__FILE__)` should work fine if the stream wrapper is gone (it won't if we don't restore it)

Comment (kukulich) [reply src/SourceLocator/Type/AutoloadSourceLocator.php:185]: Added. However it looks that PHPUnit is broken without stream wrapper restore :)

```
Warning: include(P:\Git\better-reflection\vendor\phpunit\phpunit\src\Framework\Error\Warning.php): failed to open stream: "Roave\BetterReflection\SourceLocator\Type\AutoloadSourceLocator::stream_open" call failed
"Roave\BetterReflection\SourceLocator\Type\AutoloadSourceLocator::stream_open" call failed in P:\Git\better-reflection\vendor\composer\ClassLoader.php on line 444

Warning: include(): Failed opening 'P:\Git\better-reflection\vendor\composer/../phpunit/phpunit/src/Framework/Error/Warning.php' for inclusion (include_path='.;C:\php\pear') in P:\Git\better-reflection\vendor\composer\ClassLoader.php on line 444
```

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 5 above)
Comment (kukulich) [reply src/SourceLocator/Type/AutoloadSourceLocator.php]: Renamed.

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php [hunk 10]
```diff
@@ -302,4 +307,63 @@ public function autoload(string $className) : bool
...
+
+            self::fail('No exception was thrown');
+        } catch (BrokenAutoloaderException $e) {
+            self::assertSame($e, $toBeThrown);
+        } finally {
+            spl_autoload_unregister($brokenAutoloader);
+        }
+
+        self::assertSame($previousErrorHandler, $getErrorHandler());
+        self::assertTrue(file_exists(__FILE__));
```
Comment (Ocramius) [inline test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php:367]: This will still work even with the replaced stream wrapper: what won't work (if we don't de-register it) is reading the file contents with `file_get_contents()` :D

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php (hunk 7 above)
Comment (kukulich) [reply test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: This test was useless so it's gone.

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php (hunk 8 above)
Comment (kukulich) [reply test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: Renamed.

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php (hunk 10 above)
Comment (kukulich) [reply test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: Ok. `file_get_contents` is there :)

**Comment by Ocramius** [comment]
Thanks @kukulich and @ondrejmirtes!

**Comment by Ocramius** [comment]
WRONG TAB+ENTER!!!!! DAMMIT GITHUB UI!
