### PR TITLE
#573 ensure `AutoloadSourceLocator` does not interfere with autoloading of PHP-Parser nor BetterReflection internals

### LINKED ISSUE #573: AutoloadSourceLocator::locateClassByName can crash with "Class MemoizingParser not found"
Steps to reproduce:

1) Instantiate AutoloadSourceLocator with own Parser instance (second constructor argument).
2) Ask it to locate some class reflection.
3) `locateClassByName` gets executed with the stream wrapper magic. `class_exists` leads to executing AutoloadSourceLocator constructor again, but this time, `$betterReflection->phpParser()` gets called.
4) `new MemoizingParser` fails because the class is not known and we're in a special mode with unregistered `file` wrapper so file loading does not work.

Proof of concept fix: https://github.com/ondrejmirtes/BetterReflection/commit/d7e44eeb962165ef489c498319a5ba46e3c51c0b

### PR DESCRIPTION
**Pull request by Ocramius**
Fixes #573
Fixes #575

Removed stream wrapper logic from `AutoloadSourceLocator`: using the new `FileReadTrapStreamWrapper` for that
    
This simplifies the `AutoloadSourceLocator` massively:
    
 * the constructor no longer needs to be zero-arguments (although not changed that, for BC compliance)
 * internal state slimmed down
 * magic around the object is "mostly" gone
 * allows using custom AST locators internally

### CODE REVIEW

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 1]
```diff
@@ -249,7 +225,10 @@ private function locateConstantByName(string $constantName) : ?string
 
         $constantFileName = null;
 
-        foreach (get_included_files() as $includedFileName) {
+        // Note: looking at files in reverse order, since newer files are more likely to have
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php:228]: This changes the test run from ~7s per test to ~1s per test related to constant loading :muscle:

**Comment by Ocramius** [comment]
@kukulich can you review this? I'd then be able to release (if it looks good / after adjustments)

**Comment by kukulich** [comment]
LGTM 👍 

I've ask @ondrejmirtes if he can test it in PHPStan too.

**Comment by Ocramius** [comment]
Merging then :+1: 

Thanks for the review!

**Comment by ondrejmirtes** [comment]
Please wait for my testing before releasing this. This is open-source, there's no need to hurry :)

**Comment by Ocramius** [comment]
Yep, not releasing yet :+1: 

I'm still working on mutation tests (which already found few bugs :D )

**Comment by ondrejmirtes** [comment]
@Ocramius Just tested it, works perfectly! 👍

**Comment by Ocramius** [comment]
Will cut a release then 👍
