### PR TITLE
Fixed `ReflectionClass::getImmediateInterfaces()` to only return immediately implemented interfaces

### LINKED ISSUE #643: ReflectionClass::getImmediateInterfaces() returns parent interfaces
Version: 4.3.0

`ReflectionClass::getImmediateInterfaces()` intends to `Get only the interfaces that this class implements (i.e. do not search up parent classes etc.)` but actually returns parent implemented interfaces.

Given I have following code I want to be analysed:
```php
<?php

require_once 'vendor/autoload.php';

use Roave\BetterReflection\BetterReflection;
use Roave\BetterReflection\Reflector\ClassReflector;
use Roave\BetterReflection\SourceLocator\Type\StringSourceLocator;

$code = <<<PHP
<?php
    namespace Tests\SensioLabs\Deptrac\AstRunner\Fixtures\BasicInheritance;

    interface FixtureBasicInheritanceInterfaceA { }
    interface FixtureBasicInheritanceInterfaceB extends FixtureBasicInheritanceInterfaceA { }
    interface FixtureBasicInheritanceInterfaceC extends FixtureBasicInheritanceInterfaceB { }
    interface FixtureBasicInheritanceInterfaceD extends FixtureBasicInheritanceInterfaceC { }
    interface FixtureBasicInheritanceInterfaceE extends FixtureBasicInheritanceInterfaceD { }
PHP;

$reflector = new ClassReflector(new StringSourceLocator($code, (new BetterReflection())->astLocator()));
print_r(
    array_keys(
        $reflector->reflect(
            'Tests\SensioLabs\Deptrac\AstRunner\Fixtures\BasicInheritance\FixtureBasicInheritanceInterfaceE'
        )->getImmediateInterfaces()
    )
);

```

I would expect only `FixtureBasicInheritanceInterfaceD` to be returned but currently following is returned:
```
Array
(
    [0] => Tests\SensioLabs\Deptrac\AstRunner\Fixtures\BasicInheritance\FixtureBasicInheritanceInterfaceD
    [1] => Tests\SensioLabs\Deptrac\AstRunner\Fixtures\BasicInheritance\FixtureBasicInheritanceInterfaceC
    [2] => Tests\SensioLabs\Deptrac\AstRunner\Fixtures\BasicInheritance\FixtureBasicInheritanceInterfaceB
    [3] => Tests\SensioLabs\Deptrac\AstRunner\Fixtures\BasicInheritance\FixtureBasicInheritanceInterfaceA
)
```

### PR DESCRIPTION
**Pull request by kukulich**
Fixes #643

### CODE REVIEW

File: test/unit/Reflection/ReflectionClassTest.php [hunk 1]
```diff
@@ -1493,7 +1493,7 @@ static function (ReflectionClass $interface) : string {
         sort($dInterfaces);
 
         self::assertSame(['B'], $cInterfaces);
-        self::assertSame(['A', 'B', 'C'], $dInterfaces);
+        self::assertSame(['A', 'C'], $dInterfaces);
```
Comment (kukulich) [inline test/unit/Reflection/ReflectionClassTest.php:1496]: Yes, this was bug: https://github.com/Roave/BetterReflection/blob/master/test/unit/Fixture/ClassWithInterfaces.php#L45

Comment (Ocramius) [reply test/unit/Reflection/ReflectionClassTest.php:1496]: Good catch! :muscle:
