### PR TITLE
PhpStormStubsSourceStubber fixes for case-insensitive classes/functions/constants

### LINKED ISSUE #611: PhpStormStubsSourceStubber should be case-insensitive for classes and functions
Asking for `SOAPFault` and `SoapFault` should yield the same results.

PoC fix: https://github.com/ondrejmirtes/BetterReflection/commit/3105728871436e1c34c86db23f6dfe711fd9c12d

### PR DESCRIPTION
**Pull request by kukulich**
Fixes #611

### CODE REVIEW

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php [hunk 1]
```diff
@@ -81,21 +90,27 @@ public function __construct(Parser $phpParser)
         $this->nodeTraverser = new NodeTraverser();
         $this->nodeTraverser->addVisitor(new NameResolver());
         $this->nodeTraverser->addVisitor($this->cachingVisitor);
+
+        self::$classMap    = array_change_key_case(PhpStormStubsMap::CLASSES);
+        self::$functionMap = array_change_key_case(PhpStormStubsMap::FUNCTIONS);
+        self::$constantMap = array_change_key_case(PhpStormStubsMap::CONSTANTS);
```
Comment (Ocramius) [inline src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:96]: I was looking at this and being confused: what is the casing?

PHP's default values are annoying...

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php [hunk 2]
```diff
@@ -107,37 +122,53 @@ public function generateClassStub(string $className) : ?StubData
...
-            $constantName = strtolower($constantName);
+        $lowercaseConstantName = strtolower($constantName);
+
+        if (! array_key_exists($lowercaseConstantName, self::$constantMap)) {
+            return null;
         }
 
-        if (! array_key_exists($constantName, PhpStormStubsMap::CONSTANTS)) {
+        if (array_key_exists($lowercaseConstantName, $this->constantNodes)
+            && $this->constantNodes[$lowercaseConstantName] === null
```
Comment (Ocramius) [inline src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:149]: why cam this be `null`? I see the type was expanded for that...

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php [hunk 3]
```diff
@@ -107,37 +122,53 @@ public function generateClassStub(string $className) : ?StubData
...
-        $filePath = PhpStormStubsMap::CONSTANTS[$constantName];
+        $filePath     = self::$constantMap[$lowercaseConstantName];
+        $constantNode = $this->constantNodes[$constantName] ?? $this->constantNodes[$lowercaseConstantName] ?? null;
 
-        if (! array_key_exists($constantName, $this->constantNodes)) {
+        if ($constantNode === null) {
             $this->parseFile($filePath);
+
+            if (! array_key_exists($constantName, $this->constantNodes)
+                && ! array_key_exists($lowercaseConstantName, $this->constantNodes)
```
Comment (Ocramius) [inline src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:161]: would it be better to index `$this->constantNodes` by `lowercase-string` instead of performing a double lookup here?

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php [hunk 4]
```diff
@@ -107,37 +122,53 @@ public function generateClassStub(string $className) : ?StubData
...
+            ) {
+                $this->constantNodes[$lowercaseConstantName] = null;
+
+                return null;
+            }
+
+            $constantNode = $this->constantNodes[$constantName] ?? $this->constantNodes[$lowercaseConstantName];
```
Comment (Ocramius) [inline src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:168]: this seems redundant with the above conditionals

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 2 above)
Comment (kukulich) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:149]: Constants are not case insensitive by default. They are case insensitive only if you use third parameter of `define`.

So this is optimization (line 165) if do more searches for the same constant that is not case insensitive.

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 3 above)
Comment (kukulich) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:161]: Constants are not case insensitive by default. They are case insensitive only if you use third parameter of `define`.

That's why I try both versions.

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 2 above)
Comment (Ocramius) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:149]: That still doesn't clarify the `null` scenario 🤔

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 4 above)
Comment (kukulich) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:168]: It's not. I have to update `$constantNode` after the `$this->parseFile()` call.

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 3 above)
Comment (Ocramius) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:161]: makes sense. wondering if we can make this more explicit by stashing things into a `private` method, or by adding at least a comment...

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 4 above)
Comment (Ocramius) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:168]: Yes, but the conditional right above does the same kind of lookup? Unless existence vs `null` are wildly different, at which point we need some more clarity in the data structure (`null` scenario)

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 2 above)
Comment (kukulich) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:149]: Eg. `DATE_ATOM` is not case insensitive.

First search for `date_atom` will call `->parseFile()`. It will save `date_atom` as `null` so second search for `date_atom` will not parse file again.

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 4 above)
Comment (kukulich) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php]: Added comment :)

Comment (kukulich) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php]: I hope it solve everything :D

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php [hunk 5]
```diff
@@ -67,9 +67,18 @@ final class PhpStormStubsSourceStubber implements SourceStubber
     /** @var array<string, Node\Stmt\Function_> */
     private $functionNodes = [];
 
-    /** @var array<string, Node\Stmt\Const_|Node\Expr\FuncCall> */
+    /** @var array<string, Node\Stmt\Const_|Node\Expr\FuncCall|null> */
```
Comment (Ocramius) [inline src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:70]: Could you please add a comment describing `null` here?

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php [hunk 6]
```diff
@@ -107,37 +122,52 @@ public function generateClassStub(string $className) : ?StubData
...
+        $constantNode = $this->constantNodes[$constantName] ?? $this->constantNodes[$lowercaseConstantName] ?? null;
 
-        if (! array_key_exists($constantName, $this->constantNodes)) {
+        if ($constantNode === null) {
             $this->parseFile($filePath);
+
+            $constantNode = $this->constantNodes[$constantName] ?? $this->constantNodes[$lowercaseConstantName] ?? null;
+
+            if ($constantNode === null) {
+                // Still `null` - the constant is not case-insensitive. Save `null` so we don't parse the file again for the same $constantName
```
Comment (Ocramius) [inline src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:163]: I think clarifying that `null` means "failed lookup" in the data structure is sufficient

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 5 above)
Comment (kukulich) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:70]: Done.

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php [hunk 7]
```diff
@@ -81,21 +94,27 @@ public function __construct(Parser $phpParser)
         $this->nodeTraverser = new NodeTraverser();
         $this->nodeTraverser->addVisitor(new NameResolver());
         $this->nodeTraverser->addVisitor($this->cachingVisitor);
+
+        self::$classMap    = array_change_key_case(PhpStormStubsMap::CLASSES);
```
Comment (Ocramius) [inline src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:98]: this is done at every instantiation: since that will happen once (usually), we probably should use instance variables anyway, so we simply object lifecycle semantics

File: test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php [hunk 8]
```diff
@@ -562,4 +563,99 @@ public function testNoStubForUnknownConstant() : void
...
+     * @dataProvider dataCaseInsensitiveFunction
+     */
+    public function testCaseInsensitiveFunction(string $functionName, string $expectedFunctionName) : void
+    {
+        $functionReflection = $this->functionReflector->reflect($functionName);
+
+        $this->assertSame($expectedFunctionName, $functionReflection->getName());
+    }
+
+    public function dataCaseInsensitiveConstant() : array
```
Comment (Ocramius) [inline test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php:615]: Is there a scenario around case-sensitive constants (that shouldn't be available if looked up with the wrong casing)?

Comment (kukulich) [reply test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php:615]: Yes, all tested constants are case insensitive so `IdentifierNotFound` is thrown.

File: src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php (hunk 7 above)
Comment (kukulich) [reply src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php]: Done.

**Comment by Ocramius** [comment]
Thanks @kukulich!
