### PR TITLE
Fixed ReflectionClass::getReflectionConstant() in adapter for non-existent constant

### LINKED ISSUE #625: Adapter ReflectionClass::getReflectionConstant returns null but should return false
See PoC fix: https://github.com/ondrejmirtes/BetterReflection/commit/07af30d92461a6a4e34194d21ab188b32e9cfcaa

### PR DESCRIPTION
**Pull request by kukulich**
Fixes #625

### CODE REVIEW

File: src/Reflection/Adapter/ReflectionClass.php [hunk 1]
```diff
@@ -249,9 +249,12 @@ public function getConstant($name)
      */
     public function getReflectionConstant($name)
     {
-        return new ReflectionClassConstant(
-            $this->betterReflectionClass->getReflectionConstant($name),
-        );
+        $betterReflectionConstant = $this->betterReflectionClass->getReflectionConstant($name);
+        if ($betterReflectionConstant === null) {
+            return false;
```
Comment (Ocramius) [inline src/Reflection/Adapter/ReflectionClass.php:254]: PHP has such a consistent library! 🤣
