### PR TITLE
Compatibility for ReflectionClass

### LINKED ISSUE #7: Need to become "mostly" compatible with PHP's Reflection API
Compatibility is being tracked in [compatibility.md](https://github.com/Roave/BetterReflection/blob/master/docs/compatibility.md). We need to aim for all features it is *possible* to implement. Unfortunately we cannot implement "all" the functionality, for example:

* Extension-related things `ReflectionExtension` - I don't think we have a way to access the information required by this, nor to tie it all up with our userland reflection (I may be wrong?) - see #15 
* Methods `ReflectionMethod->invoke` as we are not actually loading the classes, we cannot really invoke methods (yes, it's _technically_ possible, but not logical) - see #14 
* State modifications like `ReflectionProperty->setAccessible` and `ReflectionProperty->setValue` these require instances of classes, but we never instantiate classes - see #14 
* Instance-requiring `ReflectionObject` simply because it requires an instance, we cannot implement it, because that would require the class to be loaded - see #16 
* `ReflectionFunctionAbstract->isClosure` can't be implemented currently - see #37 
* Internal reflection is not currently possible - see #38 

## Compatibility summary
* [x] ReflectionClass - PR #59
* [x] ReflectionFunctionAbstract - PR #40
* [x] ReflectionMethod - PR #58
* [x] ReflectionParameter - PR #56
* [x] ReflectionFunction - PR #40
* [x] ReflectionProperty - PR #9

### PR DESCRIPTION
**Pull request by asgrim**
This PR brings about "most" compatibility for `ReflectionClass`, thus merging this will finally resolve #7.

### General
* [x] Rebase onto master before merge (#60 may cause conflict)
* [x] getParentClass
* [x] getDefaultProperties
* [x] getDocComment
* [x] getStartLine
* [x] getEndLine
* [x] hasConstant
* [x] hasMethod
* [x] hasProperty
* [x] isInternal
* [x] isUserDefined
* [x] isAbstract
* [x] isFinal
* [x] getModifiers

### Trait-related
* [x] getTraits
* [x] getTraitNames
* [x] getTraitAliases - waiting for PR merge: phpDocumentor/TypeResolver#9
* [x] isTrait

### Interface-related
* [x] getInterfaceNames
* [x] getInterfaces
* [x] isInterface

### Needs parent/interface/trait hierarchy
* [x] isCloneable
* [x] isInstance
* [x] isInstantiable
* [x] isIterateable
* [x] isSubClassOf
* [x] implementsInterface

### Other stuff
* [x] Inject `BetterReflection\Reflector\Reflector` instead of a `SourceLocator` to things like `getTraits`, `getInterfaces`, `getParentClass` (and other related methods)

### CODE REVIEW

File: src/Reflection/ReflectionClass.php [hunk 1]
```diff
@@ -182,6 +210,22 @@ public function getMethod($methodName)
     }
 
     /**
+     * Does the class have the specified method method?
+     *
+     * @param $methodName
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php]: string

File: src/Reflection/ReflectionClass.php [hunk 2]
```diff
@@ -209,6 +253,17 @@ public function getConstant($name)
     }
 
     /**
+     * Does this class have the specified constant?
+     *
+     * @param $name
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php]: string

File: src/Reflection/ReflectionClass.php [hunk 3]
```diff
@@ -246,6 +301,30 @@ public function getProperty($name)
     }
 
     /**
+     * Does this class have the specified property?
+     *
+     * @param $name
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php]: string

File: src/Reflection/ReflectionClass.php [hunk 4]
```diff
@@ -260,4 +339,288 @@ public function getLocatedSource()
...
+    {
+        return (int)$this->node->getAttribute('startLine', -1);
+    }
+
+    /**
+     * Get the line number that this class ends on.
+     *
+     * @return int
+     */
+    public function getEndLine()
```
Comment (Ocramius) [inline src/Reflection/ReflectionClass.php]: As suggested, getting the column may also be very interesting

Comment (asgrim) [inline src/Reflection/ReflectionClass.php]: Added #68

**Comment by Ocramius** [comment]
> * [ ] Inject `BetterReflection\Reflector\Reflector` instead of a `SourceLocator` to things like `getTraits`, `getInterfaces`, `getParentClass` (and other related methods)

Consider using just the internal reflector, or modifying the reflector at runtime (I don't see a use-case for it, though)

**Comment by asgrim** [comment]
Note - `ReflectionClass` doesn't actually have access to an internal
`Reflector` as this never gets injected... so I think for this to work it
would have to be injected in the static constructor.

**Comment by asgrim** [comment]
Note - `ReflectionClass` doesn't actually have access to an internal
`Reflector` as this never gets injected... so I think for this to work it
would have to be injected in the static constructor.
