### PR TITLE
Fixing AutoloadSourceLocator when multiple PSR-0/4 directories are possible

### LINKED ISSUE #384: AutoloadSourceLocator uses the wrong directory
Hi!

In another library using this package an issue appeared which arises from here.
https://github.com/prooph/message-flow-analyzer/issues/2

After some investigation i can summarize it to below facts.

Given my vendor directory, fulfilled from composer, has two packages with the same namespace, but different directories in which the code lies by using PSR-4.
e.g.
- zendframework/zend-expressive-router
- zendframework/zend-expressive-fastroute

And i use composers autoloader and he reckons to uses first the fastroute package and router afterwards. (Was the case in the linked issue)

Than this call
```php
use Roave\BetterReflection\Reflection\ReflectionClass;
$reflection = ReflectionClass::createFromName(\Zend\Expressive\Router\RouterInterface::class);
```

would raise this exception:
```
PHP Fatal error:  Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Zend\Expressive\Router\RouterInterface" could not be found in the located source 
```

The method `attemptAutoloadForIdentifier` returns this file path:
```
vendor/composer/../zendframework/zend-expressive-fastroute/src/RouterInterface.php
```
which is properly wrong and should be:
```
vendor/composer/../zendframework/zend-expressive-router/src/RouterInterface.php
```

This only happens if the `$prefixDirsPsr4` array from `vendor/composer/autoload_static.php` contains a like this:
```php
        'Zend\\Expressive\\Router\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-expressive-fastroute/src',
            1 => __DIR__ . '/..' . '/zendframework/zend-expressive-router/src',
        ),
```

But not if the router is the first value in that array.

Perhaps this is an issue from composer, but since the nativ reflection from php under same circumstances works like a charm, I would drop it here. sorry ;)

```php
$reflection = new \ReflectionClass(\Zend\Expressive\Router\RouterInterface::class);
echo $reflection->getFileName(); #vendor/zendframework/zend-expressive-router/src/RouterInterface.php
```

Thanks!

### PR DESCRIPTION
**Pull request by moufmouf**
This PR fixes #384.

The issue was that Composer autoloader is scanning the PSR-4 directories that may contain the file.

**Composer's ClassLoader.php excerpt**:
```php
    foreach ($this->prefixDirsPsr4[$search] as $dir) {
        if (file_exists($file = $dir . $pathEnd)) {
            return $file;
        }
    }
```

The call to `file_exists` was always returning `true`, because of the way the `AutoloadSourceLocator::url_stat` was written.

I reimplemented the `url_stat` to actually unregister the stream wrapper, fall back to the real stream wrapper, do the real "stat" call and then re-register the stream wrapper.

The code is strongly inspired from PHP-VCR so thanks to PHP-VCR folks for the idea :)

Note: The first commit is a failing test to demonstrate #384 issue.

### CODE REVIEW

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 1]
```diff
@@ -183,31 +183,30 @@ public function stream_open($path, $mode, $options, &$opened_path) : bool
...
      * @param string $path
-     * @param int    $flags
+     * @param int    $flags|false
      * @return mixed[]
      * @see https://php.net/manual/en/class.streamwrapper.php
      * @see https://php.net/manual/en/streamwrapper.url-stat.php
      * @phpcsSuppress SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingParameterTypeHint
      */
-    public function url_stat($path, $flags) : array
+    public function url_stat($path, $flags)
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php]: The `array` return type was removed, but the documented type is still `mixed[]`: what's going on here?

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 2]
```diff
@@ -183,31 +183,30 @@ public function stream_open($path, $mode, $options, &$opened_path) : bool
...
-
-        return array_merge(array_values($assoc), $assoc);
+        stream_wrapper_restore('file');
+
+        if ($flags & STREAM_URL_STAT_QUIET) {
+            set_error_handler(function () {
+                // Use native error handler
+                return false;
+            });
+            $result = @stat($path);
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php]: Oooh, I like 👍

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 3]
```diff
@@ -183,31 +183,30 @@ public function stream_open($path, $mode, $options, &$opened_path) : bool
...
-            'mtime' => time(),
-            'ctime' => time(),
-            'blksize' => 4096,
-            'blocks' => 8,
-        ];
-
-        return array_merge(array_values($assoc), $assoc);
+        stream_wrapper_restore('file');
+
+        if ($flags & STREAM_URL_STAT_QUIET) {
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php]: Please import constants and used functions

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 4]
```diff
@@ -183,31 +183,30 @@ public function stream_open($path, $mode, $options, &$opened_path) : bool
...
+                return false;
+            });
+            $result = @stat($path);
+            restore_error_handler();
+        } else {
+            $result = stat($path);
+        }
+
+        stream_wrapper_unregister('file');
+        stream_wrapper_register('file', self::class);
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php]: The code seems to restore the original wrapper, and then set this one again: perhaps the `stat()` approach allows for getting rid of the override in other code locations as well?

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php [hunk 5]
```diff
@@ -213,4 +214,15 @@ public function testReturnsNullWithInternalFunctions() : void
                 )
         );
     }
+
+    public function testCanAutoloadPsr4ClassesInpotentiallyMultipleDirectories() : void
```
Comment (Ocramius) [inline test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: `Inpotentially` or `InPotentially`?

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php [hunk 6]
```diff
@@ -4,6 +4,7 @@
 
 namespace Roave\BetterReflectionTest\SourceLocator\Type;
 
+use phpDocumentor\Reflection\DocBlock\ExampleFinder;
```
Comment (Ocramius) [inline test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: Let's please use a test asset to verify this: relying on the paths defined internally by phpDocumentor is not safe, as that's not part of the API.

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 4 above)
Comment (moufmouf) [reply src/SourceLocator/Type/AutoloadSourceLocator.php]: I'm not sure.

The only other function overriden is:

```php
    public function stream_open($path, $mode, $options, &$opened_path) : bool
    {
        self::$autoloadLocatedFile = $path;
        return false;
    }
```

If makes sense to return false, because the call to "stream_open" is triggered by `include "the_file.php"`. If we used the same approach for "stream_open", the file would be really included. If there is a syntax error in the PHP file, PHP will crash. But with the current approach, the file is not included and therefore, syntax errors are analyzed by PHP-parser and throws a nice exception.

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 3 above)
Comment (moufmouf) [reply src/SourceLocator/Type/AutoloadSourceLocator.php]: Fixed :)

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 1 above)
Comment (moufmouf) [reply src/SourceLocator/Type/AutoloadSourceLocator.php]: Fixed

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php (hunk 6 above)
Comment (Ocramius) [reply test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: @moufmouf nah, let's leave composer completely alone and register an autoloader in the test:

Pseudo-code:

```php
spl_autoload_register(function (string $className) : bool {
    if ($className !== The\Test\Asset::class) { return false; }

    if (file_exists('path/to/non/existing/stuff.php')) {
        return false;
    }

    require_once 'path/to/existing/stuff.php';
    return true;
});
```

Comment (moufmouf) [reply test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: Woot! Excellent idea! I'm on it.

Comment (Ocramius) [reply test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: Remember: `class_exists($className, false)` MUST yield `false` after running this.

File: test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php [hunk 7]
```diff
@@ -217,12 +217,31 @@ public function testReturnsNullWithInternalFunctions() : void
...
         self::assertNotNull(
             (new AutoloadSourceLocator($this->astLocator))
                 ->locateIdentifier(
                     $this->getMockReflector(),
-                    new Identifier(ExampleFinder::class, new IdentifierType(IdentifierType::IDENTIFIER_CLASS))
+                    new Identifier(AutoloadableClassWithTwoDirectories::class, new IdentifierType(IdentifierType::IDENTIFIER_CLASS))
                 )
         );
+
+        spl_autoload_unregister([$this, 'autoload']);
```
Comment (Ocramius) [inline test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php]: Please also ensure that the class does not exist at this point in the execution.

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 4 above)
Comment (moufmouf) [reply src/SourceLocator/Type/AutoloadSourceLocator.php]: Done. Tried to explain the process in the docblock: https://github.com/moufmouf/BetterReflection/blob/2d0ea4440eb82611f26cf972bfbfe71c03dd4306/src/SourceLocator/Type/AutoloadSourceLocator.php#L183-L185
Is that good enough?

File: src/SourceLocator/Type/AutoloadSourceLocator.php [hunk 8]
```diff
@@ -180,34 +180,35 @@ public function stream_open($path, $mode, $options, &$opened_path) : bool
...
     /**
-     * Must be implemented to return some data so that calls like is_file will work.
+     * url_stat is triggered by calls like "file_exists". The call to "file_exists" must not be overloaded.
+     * This function restores the original "file" stream, issues a call to "stat" to get the real results,
+     * and then re-registers the AutoloadSourceLocator stream wrapper.
      *
      * @param string $path
      * @param int    $flags
-     * @return mixed[]
+     * @return mixed[]|false
```
Comment (Ocramius) [inline src/SourceLocator/Type/AutoloadSourceLocator.php]: `false` is not a type

File: src/SourceLocator/Type/AutoloadSourceLocator.php (hunk 4 above)
Comment (Ocramius) [reply src/SourceLocator/Type/AutoloadSourceLocator.php]: :100:

**Comment by Ocramius** [comment]
@moufmouf about my comment at https://github.com/Roave/BetterReflection/issues/384#issuecomment-346900693:

 > file might be valid and readable, but it may not contain the class.

Any thoughts on this?

The scenario would be for an autoloader that stats multiple *existing* files. Separate issue? Unrealistic?

**Comment by moufmouf** [comment]
@Ocramius : Also the problem could happen for very specific autoloaders, I think the problem cannot happen with the standard Composer autoloader (I haven't done the test...).

Let's assume we have a file named `Foo.php` that does not contain the `Foo` class:

**Foo.php**
```
<?php
// Commented for some reason by the author.
/* class Foo { } */
```

Here is what will happen:

In **AutoloadSourceLocator.php**:
```php
protected function createLocatedSource(Identifier $identifier) : ?LocatedSource
    {
        $potentiallyLocatedFile = $this->attemptAutoloadForIdentifier($identifier);

        if (! ($potentiallyLocatedFile && file_exists($potentiallyLocatedFile))) {
            return null;
        }

        return new LocatedSource(
            file_get_contents($potentiallyLocatedFile),
            $potentiallyLocatedFile
        );
    }
```

`$this->attemptAutoloadForIdentifier` will return the path to `Foo.php`.

Now, this function is called in the stack by `locateIdentifier`:

In **AbstractSourceLocator.php**:
```php
    public function locateIdentifier(Reflector $reflector, Identifier $identifier) : ?Reflection
    {
        $locatedSource = $this->createLocatedSource($identifier);

        if (! $locatedSource) {
            return null;
        }

        try {
            return $this->astLocator->findReflection($reflector, $locatedSource, $identifier);
        } catch (IdentifierNotFound $exception) {
            return null;
        }
    }
```

As far as I can tell, the call to `$this->astLocator->findReflection` should throw a `IdentifierNotFound` exception that will be catched. So we return `null` which is exactly what we want.

So everything is good so far.

Now, let's study another use case:

We might have 2 `Foo.php`, one with the class and one without the class. It might be interesting to scan all files to find the class in the correct file. Yet, that would be a bad idea I think, because Composer's autoloader would fail to autoload the file. By default, the current implementation of Composer's autoloader is including that first file it finds, and ignores the others.

Sure, if Composer is fixing this behaviour, we will have to change the `AutoloadSourceLocator` again, but that's pretty unlikely to me.

By the way, thanks a lot for the thorough code review!

**Comment by Ocramius** [comment]
> Yet, that would be a bad idea I think

I think that too, I'm just wondering whether the tool (BetterReflection) should care.

I think we should consider it for a separate issue then: will open it after merging here :+1:

**Comment by Ocramius** [comment]
Thanks @moufmouf!
